version: '3.9'

services:
  front:
    build:
      context: ./front/
    container_name: front
    expose:
      - 3000
    ports:
      - "3000:3000"
    env_file:
      - "./front/.env"
    volumes:
      - './front:/front'
      - '/front/node_modules'
    stdin_open: true
    tty: true
    networks:
      - backend

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: dunning
      MONGO_INITDB_ROOT_PASSWORD: kruger6
    volumes:
      # -v 옵션 (다렉토리 마운트 설정)
      - './data/mongodb:/data/db'
    networks:
      - backend

  server:
    build:
      context: ./back/
    container_name: back
    restart: "on-failure"
    expose:
      - 5000
    ports:
      - "5000:5000"
    env_file:
      - "./back/.env"
    volumes:
      - './back:/back'
      - '/back/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - backend

  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./front/build:/front/build  
    networks:
      - backend

networks:
  backend:
    driver: bridge
