version: '3.3'

services:
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./front/build:/front/build

  front:
    build:
      context: ./front/
    container_name: front
    expose:
      - 3000
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'

  server:
    build:
      context: ./back/
    container_name: back
    restart: "on-failure"
    expose:
      - 5000
    volumes:
      - './back:/back'
      - '/back/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true